### ISSUE TITLE
Different results with 0.8, 0.10, 0.11 x86 and 0.11 x64 with Plextor Premium

### ISSUE THREAD

**Issue by malvarenga123** [xavery/cachex#1] opened 2023-09-26 17:49 UTC
Hi there, @xavery.
I wanted to test my Plextor drive to see if I could use `--usefua` with EAC, but I'm getting different results with v0.8 from spath and v0.11 from you:

```
H:\DiscImageCreator>cachex -i -p -k -c -n 3 l:

CacheExplorer 0.8 - spath@cdfreaks.com

Drive on L is  PLEXTOR  CD-R   PREMIUM   1.07

[+] Buffer size: 8192 kB, read cache is enabled
[+] Supported read commands: BEh A8h(FUA) 28h(FUA) D4h(FUA) D5h(FUA) D8h(FUA)
[+] Plextor flush command: accepted
[+] Plextor flush tests: 3/3
[+] Testing cache line size:
 1171 kB / 510 sectors
 1171 kB / 510 sectors
 1171 kB / 510 sectors
[+] Testing cache disabling: not supported
```
```
H:\DiscImageCreator>cachex-amd64.exe -i -p -k -c -n 3 l:

CacheExplorer 0.11 - https://github.com/xavery/cachex, based on
CacheExplorer 0.9 - spath@cdfreaks.com

Drive on l: is  PLEXTOR  CD-R   PREMIUM   1.07

[+] Supported read commands: BEh A8h(FUA) 28h(FUA) 28h_12(FUA) D4h(FUA) D5h(FUA)
 D8h(FUA)
[+] Plextor flush command: rejected
[+] Testing cache line size:
 1171 kB / 510 sectors
 1171 kB / 510 sectors
 1171 kB / 510 sectors
[+] Testing cache disabling: not supported
```
Any idea of what could be happening?

**Comment by malvarenga123** [comment] 2023-09-26 17:52
Just tested with 0.10 and the results are similar to 0.8

```
H:\DiscImageCreator>cachex010 -i -p -k -c -n 3 l:

CacheExplorer 0.10 - https://github.com/xavery/cachex, based on

CacheExplorer 0.9 - spath@cdfreaks.com

Drive on l: is  PLEXTOR  CD-R   PREMIUM   1.07

[+] Buffer size: 8192 kB, read cache is enabled
[+] Supported read commands: BEh A8h(FUA) 28h(FUA) D4h(FUA) D5h(FUA) D8h(FUA)
[+] Plextor flush command: accepted
[+] Plextor flush tests: 3/3
[+] Testing cache line size:
 1171 kB / 510 sectors
 1171 kB / 510 sectors
 1171 kB / 510 sectors
[+] Testing cache disabling: not supported
```

**Comment by malvarenga123** [comment] 2023-09-26 17:54
Also very different results with 0.11 x86:

```
H:\DiscImageCreator>cachex-x86 -i -p -k -c -n 3 l:

CacheExplorer 0.11 - https://github.com/xavery/cachex, based on
CacheExplorer 0.9 - spath@cdfreaks.com

Drive on l: is  PLEXTOR  CD-R   PREMIUM   1.07
, read cache is enabled
[+] Supported read commands: A8h 28h_12 D8h
[+] Plextor flush command: rejected
[+] Testing cache line size:
 no cache detected
 no cache detected
 no cache detected
[+] Testing cache disabling: not supported
```

**Comment by lighterowl** [comment] 2023-09-28 17:49
Hey there, thanks for the report.

The most significant change in 0.11 was https://github.com/xavery/cachex/commit/a4a3676e11344231a44a87635d7c3a8ee22237c7 , which added checking if the command issued to the drive actually succeeded, or rather if the drive reported successfully executing/processing it. Previous versions of the code only checked if the system call succeeded which is not the same thing, as the OS could report success as long as the command had been successfully sent to the drive.

I presume this is the reason why pre-0.11 report `Plextor flush command: accepted` which is actually a false positive, while 0.11 correctly reports it as rejected.

However, I have no intimate knowledge about how the drives work and perhaps there are cases where the status field should be ignored. If you have alternative means of verifying whether this command works properly or documentation, please share. I don't have any FUA-capable drives myself unfortunately.

I have no idea what's up with the x86 version though. Best to stay away from it for now, from the looks of it.

**Comment by malvarenga123** [comment] 2023-09-29 15:55
> If you have alternative means of verifying whether this command works properly or documentation, please share. I don't have any FUA-capable drives myself unfortunately.

I've only tested this with EAC and it seems to work, because ripping is much faster, but I can't be sure.
My suggestion would be talking to @saramibreak or @superg, both of them have deeper knowledge of Plextor drives.
Also, you could take a look at their ripping code:
https://github.com/saramibreak/DiscImageCreator
https://github.com/superg/redumper

**Comment by lighterowl** [comment] 2023-09-29 19:11
> I've only tested this with EAC and it seems to work, because ripping is much faster, but I can't be sure.

Unfortunately, the fact alone that ripping is faster does not say anything. The main reason why EAC tries to disable the drive's cache has to do with error detection : generally, when EAC tries to re-read a sector, it wants to be sure that it's actually being re-read from the drive instead of just returned from the cache. I wasn't able to find what `--usefua` is actually supposed to be doing^, but it's very possible that the flush command fails and your rip process simply uses the cache which explains why it's so much faster.

Unless you have a very scratched CD - which is when differences between actually-accessed sectors and cache-accessed sectors pop up, you won't be able to make any guesses about what the drive actually does.

^ I would expect it to issue read commands with the FUA bit set but according to [this](https://www.audioasylum.com/cgi/t.mpl?f=digital&m=130152) it issues the "Plextor flush command" which is also [confirmed by spath](https://hydrogenaud.io/index.php/topic,45996.msg409440.html#msg409440).

^^ Actually, one of the comments that [spath themselves left at Hydrogenaudio](https://hydrogenaud.io/index.php/topic,14489.msg148257.html#msg148257) says that "It is possible on most drives to disable the cache (...) by using the FUA (Force Unit Access) bit with your read commands " - so I wasn't that wrong when I expected EAC to just toggle the FUA bit in read commands. Unfortunately, it seems like FUA support in read commands has been discussed since at least 1998 but never actually made it into EAC for reasons that spath explains in some of their posts. `tl;dr` it's a real mess that mostly seems to boil down to "people problems"

**Comment by malvarenga123** [comment] 2023-09-30 17:25
Using the debug command, I've noticed that v0.8 and v0.10 return 0 for the Plextor flush command, while v0.11 returns 255.
After trying to look around the code to see where "result" would be updated from 255 (the default value from result.h) to 0, it all comes down to PlextorFUAFlush.
So my guess is that commit b32cff2 breaks it, as Plextor drives seem to have a very specific way (the old PlextorFUAFlush) to check for this command, which won't work using a "straightforward Read_28h_12 call"

Edit: Just something else I noticed is that v0.11 does not display this first line:
`[+] Buffer size: 8192 kB, read cache is enabled`

**Comment by superg** [comment] 2023-09-30 17:43
I briefly overviewed the thread, it is unknown to us @redump.org that 0xD8 plextor command has FUA bit.
It's not defined that way in the official early standard doc (Pioneer I think) - 0xD8 CDB doesn't have that field at all.
If we want uncached read, we use 0xA8 with FUA set, ignore the read data and then read the same sector with 0xD8.
Although I never tested it by forcing that CDB bit manually.

**Comment by lighterowl** [comment] 2023-10-01 10:56
@superg Thanks. cdparanoia [seems to think it does](https://github.com/ngc7293/cdparanoia/blob/master/interface/scsi_interface.c#L902) but that doesn't really prove a lot since those commands are naturally undocumented.

@malvarenga123 That can't be it, the CDB generated by both functions is identical ([godbolt](https://gcc.godbolt.org/z/n1xeMMzdf)). The fact that you're seeing `ScsiStatus` equal to 255 suggests that something's seriously off though, as there is no code path where that variable wouldn't be updated with the [actual result received from `DeviceIoControl`](https://github.com/xavery/cachex/blob/v0.11/cachex_win.h#L66). In fact, that place is the only write to `ScsiStatus` - except the analogous function in the Linux platform implementation, of course. :thinking:

**Comment by malvarenga123** [comment] 2023-10-01 16:48
> The fact that you're seeing `ScsiStatus` equal to 255 suggests that something's seriously off though, as there is no code path where that variable wouldn't be updated with the [actual result received from `DeviceIoControl`](https://github.com/xavery/cachex/blob/v0.11/cachex_win.h#L66)

That's really strange.
You may be able to debug this even without a Plextor drive, though:

```
H:\DiscImageCreator>cachex010 -d -i -p -n 3 j:

CacheExplorer 0.10 - https://github.com/xavery/cachex, based on

CacheExplorer 0.9 - spath@cdfreaks.com

Drive on j: is  ASUS     BW-16D1HT        3.02

[+] Buffer size: 4064 kB, read cache is enabled
[+] Supported read commands: BEh A8h(FUA) 28h(FUA) D4h(FUA) D5h(FUA) D8h(FUA)
[+] Plextor flush command: accepted (status = 0)
[+] Plextor flush tests:
info: using command BEh
info: 3 test(s), c/nc ratio: 4, burst: 1, max: 1000
 128.35 ms / 3.42 ms -> 128.27 ms / 86.40 ms
 128.31 ms / 3.26 ms -> 128.23 ms / 86.58 ms
 128.15 ms / 3.28 ms -> 128.23 ms / 86.04 ms
result: 3/3

H:\DiscImageCreator>cachex-x64 -d -i -p -n 3 j:

CacheExplorer 0.11 - https://github.com/xavery/cachex, based on
CacheExplorer 0.9 - spath@cdfreaks.com

Drive on j: is  ASUS     BW-16D1HT        3.02

[+] Supported read commands: BEh A8h(FUA) 28h(FUA) 28h_12(FUA) D4h(FUA) D5h(FUA) D8h(FUA)
[+] Plextor flush command: rejected (status = 255)
```

**Comment by lighterowl** [comment] 2023-10-01 20:11
Ok, my bad, it all came down to using uninitialised memory. Turns out that `DeviceIoControl(IOCTL_SCSI_PASS_THROUGH_DIRECT)` doesn't always write to all of its struct members when it's not necessary. I would've expected it to always write to `sptd.ScsiStatus` with the actual status but apparently it doesn't, presumably only changing that value only when the status is non-zero. [Smartmontools](https://github.com/mirror/smartmontools/blob/4591526a9de7dceca255783390236bcdf61778b7/os_win32.cpp#L2936) and [PyBadUSB](https://github.com/x64x6a/PyBadUSB/blob/96c7d9d34573755f1a59b9b4f6a3c999fe9a5976/lib/scsi.cpp#L37) also clear out the struct before passing it down to `DeviceIoControl` so in all fairness this is something that cachex should've always done.

> Edit: Just something else I noticed is that v0.11 does not display this first line:
> `[+] Buffer size: 8192 kB, read cache is enabled`

This is caused by the same thing, as printing the buffer/cache information received from the drive is wrapped in a `if(result)` block that inspected the botched `ScsiStatus`. Printing the data returned from INQUIRY, however, isn't guarded by that block so the drive name still appears.

Both amd64 and x86 return the same results now :
```
CacheExplorer 0.12 - https://github.com/xavery/cachex, based on
CacheExplorer 0.9 - spath@cdfreaks.com

Drive on d: is  ASUS     SDRW-08U7M-U     A101

[+] Buffer size: 768 kB, read cache is enabled
[+] Supported cache flush commands: A8h 28h 28h_12 D4h D5h D8h
[+] Supported read commands: BEh A8h(FUA) 28h(FUA) 28h_12(FUA) D4h(FUA) D5h(FUA) D8h(FUA)
[+] Plextor flush command: accepted (status = 0)
[+] Plextor flush tests:
info: using command BEh
info: 5 test(s), c/nc ratio: 4, burst: 1, max: 1000
 1.4e+02 ms / 3.6 ms -> 1.4e+02 ms / 67 ms
 1.4e+02 ms / 3.6 ms -> 1.4e+02 ms / 67 ms
 1.4e+02 ms / 4.9 ms -> 1.4e+02 ms / 6 ms
 1.4e+02 ms / 3.9 ms -> 1.4e+02 ms / 65 ms
 1.4e+02 ms / 3.6 ms -> 1.4e+02 ms / 67 ms
result: 4/5
```

```
CacheExplorer 0.12 - https://github.com/xavery/cachex, based on
CacheExplorer 0.9 - spath@cdfreaks.com

Drive on d: is  ASUS     SDRW-08U7M-U     A101

[+] Buffer size: 768 kB, read cache is enabled
[+] Supported cache flush commands: A8h 28h 28h_12 D4h D5h D8h
[+] Supported read commands: BEh A8h(FUA) 28h(FUA) 28h_12(FUA) D4h(FUA) D5h(FUA) D8h(FUA)
[+] Plextor flush command: accepted (status = 0)
[+] Plextor flush tests:
info: using command BEh
info: 5 test(s), c/nc ratio: 4, burst: 1, max: 1000
 1.4e+02 ms / 5.1 ms -> 1.4e+02 ms / 64 ms
 1.4e+02 ms / 3.9 ms -> 1.4e+02 ms / 66 ms
 1.4e+02 ms / 3.6 ms -> 1.4e+02 ms / 67 ms
 1.4e+02 ms / 4.5 ms -> 1.4e+02 ms / 4.2 ms
 1.4e+02 ms / 3.6 ms -> 1.4e+02 ms / 67 ms
result: 4/5
```

Fix is in 21c11ab. I deleted the 0.11 release as it's essentially unusable. Printing non-integer values could also use a rework, something I missed when changing printf calls to iostreams.

**Comment by superg** [comment] 2023-10-08 13:47
> @superg Thanks. cdparanoia [seems to think it does](https://github.com/ngc7293/cdparanoia/blob/master/interface/scsi_interface.c#L902) but that doesn't really prove a lot since those commands are naturally undocumented.
I just checked it and can confirm that setting fua bit for D8 command fails with SCSI error. Verified on one of my good plextors (PX-W5224TA).

D8 command is documented in SCSI-2 reference manual by Pioneer: https://www.pioneerelectronics.com/pio/pe/images/portal/cit_3424/31636562SCSI-2RefManV31.pdf
It doesn't define FUA bit but there is 5-bit reserved field where it's usually located in other commands.

At some point I've read somewhere that D8 FUA might be implemented for native SCSI drives. I can't find that source and knowing PLEXTOR drives, SCSI model variant is using the same firmware as it's IDE twin so this is impossible. The only exception would be an early PX-40TS but that's not an option for modern system.

Also I couldn't help but notice that "Supported read commands" for a number of drives as pasted here in this thread always contains D8h(FUA). This is incorrect for most of the drives.
For instance, ASUS BW-16D1HT doesn't even have D8 command.

**Comment by malvarenga123** [comment] 2023-11-21 22:20
Hello again, @xavery. Are you planning on releasing v0.12 binaries? There are no artifacts in Github actions.

**Comment by lighterowl** [comment] 2023-11-22 09:00
> Hello again, @xavery. Are you planning on releasing v0.12 binaries? There are no artifacts in Github actions.

I will once I finally get around to reverting the changes related to printing floats. Thanks for reminding me about this.

**Comment by lighterowl** [comment] 2023-11-23 21:16
v0.12 is now live at https://github.com/xavery/cachex/releases/tag/v0.12. Closing.

**Closed as completed by lighterowl** 2023-11-23 21:16 UTC
